---
title: "CV"
output: html_document
---

## Key Research Skills
-	R statistical programming environment for biostatistical and behavioural modelling
-	Building and implementing Bayesian mark-recapture models in RStan
-	Analysing patterns of movement and behaviour from telemetry data in different environments
- Use of GIS software and integration with formal statistical analysis

<br>

## Education
- 2015-2018	<u>Newcastle University - PhD School of Natural and Environmental Sciences.</u><br> 
"Movement patterns of the European lobster Homarus gammarus: investigating the effects of habitat use and behaviour patterns on catchability."
- 2005-2006	<u>University of Edinburgh - MSc Forest Ecology and Management.</u><br> 
"Scarlet macaw food choice in relation to fruiting phenology and availability."
- 2000-2004	<u>University of Glasgow - BSc (Hons) Zoology, 2:2.</u><br>

<br>

## Employment History
- 2019 --	<u>Postdoctoral Fellow, Integrative Biology, University of Windsor, ON.</u><br> 
Developing acoustic telemetry Bayesian mark-recapture models using RStan to estimate survival of Greenland halibut and support the development of an Inuit community fishery. Assisting with the supervision of student projects, and contributing to Arctic-based telemetry field work.<br>
- 2011-2014	<u>Research Assistant, University of Highlands & Islands, U.K.</u><br> 
Assisting on a variety of collaborative multidisciplinary EU projects that investigated the potential ecological effects of marine renewable energy.<br> 
--Energymare - Monitoring the potential for fish aggregation around wave energy converters using underwater cameras.<br>
--Hebridean Marine Energy Futures - Investigating the potential ecological impact of wave renewable energy devices on seabird distributions. Spatial analysis and statistical modelling of seabird distributions using a long-term dataset of land-based seabird observations, before and after deployment of a wave energy device.<br> 
--MaREE - Investigating the overlap of seabird dive profiles and habitat use with marine renewable sites. Deploying GPS and TDR tags on seabirds.<br>
- 2010-2011	<u>Field Ecologist, Food and Environment Research Agency, UK.</u><br> 
Field and laboratory support for projects within the Wildlife Management team. Assisting with the trapping of small to large mammals, and deployment of RADAR to monitor bird movement through offshore energy developments.<br> 
 - 2009	<u> Senior Research Assistant - Royal Society for the Protection of Birds, UK</u><br> 
Completing extensive surveys of upland breeding birds, and nest trapping shore birds to attach VHF tags to both adults and chicks.<br>

<br>

## Teaching Experience
<b>Lecturing</b>	-- Community Ecology (final year undergraduate), University of Windsor.<br>
<b>Undergraduate Supervision</b><br>
-- Investigating differing detection efficiencies of VMT and VR2 acoustic receivers (University of Windsor, 2019). <br>
-- Habitat use and home-range analysis of GPS collared vervet monkeys Chlorocebus aethiops on St Kitts (Newcastle University, 2017 and 2018). <br>
<b>Computer practicals</b> Statistics using R (MSc), Ecological modelling (BSc), and Introduction to GIS (BSc).<br>
<b>Field Courses</b> Residential field courses: Supervision of small groups during independent projects.<br> 
-- Ornithology: Field visits to practice bird identification and daily classroom revision sessions.<br>
-- Small Mammal Ecology: small mammal trapping, radio-tracking, and home range analyses. <br>  

<br>

## Additional relevant skills
<b>Peer-review</b>	Marine Ecology Progress Series, Fisheries Management and Ecology.<br>
<b>Software</b>	Experienced LaTeX user.<br>
<b>Fieldwork</b>	Boat-based fieldwork - up to 2 weeks at sea. Acoustic receiver deployment and maintenance, acoustic tagging of lobsters and crabs, and fish dissections and sampling.<br> 
Bird ringing/banding permit holder - British Trust for Ornithology.<br>
<b>Outreach</b>	Science-based Stand-up Comedy, The Stand Comedy Club, Newcastle.<br>
Two performances as part of Bright Club. Bright Club encourages academics to share their research experiences using the medium of comedy with adult audiences that are not usually targeted as part of traditional outreach activities.<br>
https://www.youtube.com/watch?v=Nnou0FRtRpI April 2016 - starts 6.40 min<br>
https://www.youtube.com/watch?v=Enghu41ZEus July 2015


						 



